const fs=require('fs');
const base=require('path').join(__dirname,'..')+'/';
require('vm').runInThisContext(fs.readFileSync(base+'cube.js','utf8'));
const c=new Cube();
const assert=require('assert');
assert(c.isSolved(),'fresh cube solved');

// sexy move has order 6
for(let i=0;i<6;i++){c.turn('R',1);c.turn('U',1);c.turn('R',-1);c.turn('U',-1);}
assert(c.isSolved(),'(R U R\' U\')^6 == identity');

// single turn is not solved; 4 turns returns
c.turn('F',1); assert(!c.isSolved());
c.turn('F',1);c.turn('F',1);c.turn('F',1); assert(c.isSolved(),'F^4');

// half turn == two quarters
const a=new Cube(), b=new Cube();
a.turn('L',2); b.turn('L',1); b.turn('L',1);
assert.deepStrictEqual(a.cubies.map(x=>[x.position,x.orientation]), b.cubies.map(x=>[x.position,x.orientation]),'L2');

// scramble then invert solves
const s=randomScramble(40);
for(const m of s){const {face,quarters}=parseMove(m);c.turn(face,quarters);}
assert(!c.isSolved(),'scrambled');
for(const m of [...s].reverse()){const {face,quarters}=parseMove(m);const i=invertMove(face,quarters);c.turn(i.face,i.quarters);}
assert(c.isSolved(),'inverse scramble solves');

// every layer always has exactly 9 cubies, and centers stay put
for(const f of FACE_ORDER) assert.strictEqual(c.layer(f).length,9,'layer '+f);
for(const m of randomScramble(30)){const {face,quarters}=parseMove(m);c.turn(face,quarters);}
for(const f of FACE_ORDER){
  assert.strictEqual(c.layer(f).length,9,'layer size after scramble');
  const center=c.cubies.find(x=>x.position.filter(v=>v!==0).length===1 && x.position.every((v,i)=>v===FACES[f].axis[i]));
  assert(center.home.every((v,i)=>v===center.position[i]),'center '+f+' fixed');
}
// sticker counts: 9 of each colour visible on the cube
const counts={};
for(const cu of c.cubies) for(const f of cu.stickers) counts[f]=(counts[f]||0)+1;
assert(FACE_ORDER.every(f=>counts[f]===9), 'nine stickers per colour');
console.log('all cube model checks passed');

// The default colours must describe a cube that can actually be built. A
// mirror-image scheme (swapping just two opposite faces) looks plausible and
// is impossible, so check the palette against every orientation of a standard
// cube: white opposite yellow, green opposite blue, red opposite orange, and
// red on the right when white is up and green faces you.
{
  const REFERENCE = { U: 'white', D: 'yellow', F: 'green', B: 'blue', R: 'red', L: 'orange' };
  const axisName = (axis) =>
    FACE_ORDER.find((f) => FACES[f].axis.every((v, i) => v === axis[i]));

  // The 24 orientations, generated by composing quarter turns of the whole cube.
  const rotations = new Map();
  const key = (m) => m.flat().join(',');
  const identity = [[1,0,0],[0,1,0],[0,0,1]];
  let frontier = [identity];
  rotations.set(key(identity), identity);
  while (frontier.length) {
    const next = [];
    for (const m of frontier) {
      for (const axis of [[1,0,0],[0,1,0],[0,0,1]]) {
        const turned = multiply(rotationMatrix(axis, 90), m);
        if (!rotations.has(key(turned))) { rotations.set(key(turned), turned); next.push(turned); }
      }
    }
    frontier = next;
  }
  assert.strictEqual(rotations.size, 24, 'the rotation group has 24 elements');

  const actual = Object.fromEntries(FACE_ORDER.map((f) => [f, FACES[f].name]));
  const matches = [...rotations.values()].some((m) =>
    FACE_ORDER.every((face) => {
      // Where this face's sticker sits once the reference cube is turned by m.
      const moved = axisName(apply(m, FACES[face].axis));
      return REFERENCE[moved] === actual[face];
    })
  );
  assert(matches, 'the default colours are not any orientation of a real cube: ' + JSON.stringify(actual));

  // and the cross the course builds is the white one
  assert.strictEqual(FACES.D.name, 'white', 'the bottom face should be white');
  for (const face of FACE_ORDER) {
    assert(FACES[face].name, `face ${face} has no colour name`);
    assert(/^#[0-9a-f]{6}$/.test(FACES[face].color), `face ${face} has no colour`);
  }
}
console.log('default colours are a real cube, white on the bottom');
